/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package com.grocery.app.view;

import com.grocery.app.controller.ItemController;
import com.grocery.app.controller.impl.ItemControllerImpl;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.grocery.app.model.Item;

/**
 *
 * @author Tharindu
 */
public class ManageItemForm extends javax.swing.JDialog {
    private final ItemController itemController=new ItemControllerImpl();
    /**
     * Creates new form ManageItemForm
     */
    private String itemCode="";
    int mouseX;
    int mouseY;
    public ManageItemForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        itemICodeAddTxt = new javax.swing.JTextField();
        itemDescAddTxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        itemQTYAddTxt = new javax.swing.JTextField();
        itemUPAddTxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        itemAddBt = new javax.swing.JButton();
        itemAddClearBtn = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        itemICodeDeleteTxt = new javax.swing.JTextField();
        itemDescDeleteTxt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        itemQTYDeleteTxt = new javax.swing.JTextField();
        itemUPDeleteTxt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        itemDeleteBt = new javax.swing.JButton();
        itemDeleteClearBtn = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        itemICodeSearchTxt = new javax.swing.JTextField();
        itemDescSearchTxt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        itemQTYSearchTxt = new javax.swing.JTextField();
        itemUPSearchTxt = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        itemSearchBt = new javax.swing.JButton();
        itemSearchClearBtn = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        itemICodeUpdateTxt = new javax.swing.JTextField();
        itemDescUpdateTxt = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        itemQTYUpdateTxt = new javax.swing.JTextField();
        itemUPUpdateTxt = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        itemUpdateBt = new javax.swing.JButton();
        itemUpdateClearBtn = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Items");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jTabbedPane3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("Item Code :");

        itemICodeAddTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemICodeAddTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemICodeAddTxtActionPerformed(evt);
            }
        });

        itemDescAddTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemDescAddTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDescAddTxtActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("Description :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 102));
        jLabel20.setText("QTY :");

        itemQTYAddTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemQTYAddTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemQTYAddTxtActionPerformed(evt);
            }
        });

        itemUPAddTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemUPAddTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUPAddTxtActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 102));
        jLabel21.setText("Unit Price :");

        itemAddBt.setText("Add");
        itemAddBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddBtActionPerformed(evt);
            }
        });

        itemAddClearBtn.setText("Clear");
        itemAddClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddClearBtnActionPerformed(evt);
            }
        });

        jButton15.setText("Exit");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemICodeAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemDescAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemQTYAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemUPAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemAddBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemAddClearBtn)
                .addGap(5, 5, 5)
                .addComponent(jButton15)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(itemICodeAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(itemDescAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(itemQTYAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(itemUPAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemAddBt)
                    .addComponent(itemAddClearBtn)
                    .addComponent(jButton15))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Add", jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 102));
        jLabel22.setText("Item Code :");

        itemICodeDeleteTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemICodeDeleteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemICodeDeleteTxtActionPerformed(evt);
            }
        });

        itemDescDeleteTxt.setEditable(false);
        itemDescDeleteTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 102));
        jLabel23.setText("Description :");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 102));
        jLabel24.setText("QTY :");

        itemQTYDeleteTxt.setEditable(false);
        itemQTYDeleteTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        itemUPDeleteTxt.setEditable(false);
        itemUPDeleteTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 102));
        jLabel25.setText("Unit Price :");

        itemDeleteBt.setText("Delete");
        itemDeleteBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeleteBtActionPerformed(evt);
            }
        });

        itemDeleteClearBtn.setText("Clear");
        itemDeleteClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeleteClearBtnActionPerformed(evt);
            }
        });

        jButton18.setText("Exit");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemICodeDeleteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemDescDeleteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemQTYDeleteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemUPDeleteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemDeleteBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemDeleteClearBtn)
                .addGap(5, 5, 5)
                .addComponent(jButton18)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(itemICodeDeleteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(itemDescDeleteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(itemQTYDeleteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(itemUPDeleteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemDeleteBt)
                    .addComponent(itemDeleteClearBtn)
                    .addComponent(jButton18))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Delete", jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 102));
        jLabel26.setText("Item Code :");

        itemICodeSearchTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemICodeSearchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemICodeSearchTxtActionPerformed(evt);
            }
        });

        itemDescSearchTxt.setEditable(false);
        itemDescSearchTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 102, 102));
        jLabel27.setText("Description :");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 102));
        jLabel28.setText("QTY :");

        itemQTYSearchTxt.setEditable(false);
        itemQTYSearchTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        itemUPSearchTxt.setEditable(false);
        itemUPSearchTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 102, 102));
        jLabel29.setText("Unit Price :");

        itemSearchBt.setText("Search");
        itemSearchBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSearchBtActionPerformed(evt);
            }
        });

        itemSearchClearBtn.setText("Clear");
        itemSearchClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSearchClearBtnActionPerformed(evt);
            }
        });

        jButton21.setText("Exit");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemICodeSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemDescSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemQTYSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemUPSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemSearchBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemSearchClearBtn)
                .addGap(5, 5, 5)
                .addComponent(jButton21)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(itemICodeSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(itemDescSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(itemQTYSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(itemUPSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemSearchBt)
                    .addComponent(itemSearchClearBtn)
                    .addComponent(jButton21))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Search", jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 102, 102));
        jLabel30.setText("Item Code :");

        itemICodeUpdateTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemICodeUpdateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemICodeUpdateTxtActionPerformed(evt);
            }
        });

        itemDescUpdateTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 102, 102));
        jLabel31.setText("Description :");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 102, 102));
        jLabel32.setText("QTY :");

        itemQTYUpdateTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        itemUPUpdateTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 102, 102));
        jLabel33.setText("Unit Price :");

        itemUpdateBt.setText("Update");
        itemUpdateBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUpdateBtActionPerformed(evt);
            }
        });

        itemUpdateClearBtn.setText("Clear");
        itemUpdateClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUpdateClearBtnActionPerformed(evt);
            }
        });

        jButton24.setText("Exit");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemICodeUpdateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemDescUpdateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemQTYUpdateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemUPUpdateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemUpdateBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemUpdateClearBtn)
                .addGap(5, 5, 5)
                .addComponent(jButton24)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(itemICodeUpdateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(itemDescUpdateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(itemQTYUpdateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(itemUPUpdateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemUpdateBt)
                    .addComponent(itemUpdateClearBtn)
                    .addComponent(jButton24))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Update", jPanel13);

        jButton1.setText("View Stock");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void itemICodeAddTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemICodeAddTxtActionPerformed
        itemDescAddTxt.requestFocus();
    }//GEN-LAST:event_itemICodeAddTxtActionPerformed
    
    private void itemDescAddTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDescAddTxtActionPerformed
        itemQTYAddTxt.requestFocus();
    }//GEN-LAST:event_itemDescAddTxtActionPerformed
    
    private void itemQTYAddTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemQTYAddTxtActionPerformed
        itemUPAddTxt.requestFocus();
    }//GEN-LAST:event_itemQTYAddTxtActionPerformed
    
    private void itemUPAddTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUPAddTxtActionPerformed
        itemAddBt.doClick();
    }//GEN-LAST:event_itemUPAddTxtActionPerformed
    
    private void itemAddBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddBtActionPerformed
        try {
            boolean isAdded = itemController.addItem(new Item(itemICodeAddTxt.getText(), itemDescAddTxt.getText(), Integer.parseInt(itemQTYAddTxt.getText()), Double.parseDouble(itemUPAddTxt.getText())));
            if(isAdded){
                JOptionPane.showMessageDialog(this, "Item Added Successfully !!");
                itemAddClearBtn.doClick();
                itemICodeAddTxt.requestFocus();
            }else {
                JOptionPane.showMessageDialog(this, "Item Added Falier !!");
                itemICodeAddTxt.requestFocus();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemAddBtActionPerformed
    
    private void itemAddClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddClearBtnActionPerformed
        itemICodeAddTxt.setText("");
        itemDescAddTxt.setText("");
        itemQTYAddTxt.setText("");
        itemUPAddTxt.setText("");
        itemICodeAddTxt.requestFocus();
    }//GEN-LAST:event_itemAddClearBtnActionPerformed
    
    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton15ActionPerformed
    
    private void itemICodeDeleteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemICodeDeleteTxtActionPerformed
        try {
            String itemCode=itemICodeDeleteTxt.getText();
            this.itemCode=itemCode;
            Item item = itemController.searchItem(itemCode);
            if(item!=null){
                itemICodeDeleteTxt.setText(item.getCode());
                itemDescDeleteTxt.setText(item.getDescription());
                itemQTYDeleteTxt.setText(Integer.toString(item.getQty()));
                itemUPDeleteTxt.setText(Double.toString(item.getUnitPrice()));
            }else{
                JOptionPane.showMessageDialog(this, "No Item Found..");
                itemDescDeleteTxt.setText("");
                itemQTYDeleteTxt.setText("");
                itemUPDeleteTxt.setText("");
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ThogaKadeMW.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemICodeDeleteTxtActionPerformed
    
    private void itemDeleteBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeleteBtActionPerformed
        try {
            boolean isDeleted = itemController.deleteItem(itemICodeDeleteTxt.getText());
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Item Deleted Successfully !!");
                itemDeleteClearBtn.doClick();
                itemICodeDeleteTxt.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Item Delete Fail !!");
                itemICodeDeleteTxt.requestFocus();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ThogaKadeMW.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemDeleteBtActionPerformed
    
    private void itemDeleteClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeleteClearBtnActionPerformed
        itemICodeDeleteTxt.setText("");
        itemDescDeleteTxt.setText("");
        itemQTYDeleteTxt.setText("");
        itemUPDeleteTxt.setText("");
        itemICodeDeleteTxt.requestFocus();
    }//GEN-LAST:event_itemDeleteClearBtnActionPerformed
    
    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton18ActionPerformed
    
    private void itemICodeSearchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemICodeSearchTxtActionPerformed
        itemSearchBt.doClick();
    }//GEN-LAST:event_itemICodeSearchTxtActionPerformed
    
    private void itemSearchBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSearchBtActionPerformed
        try {
            Item item = itemController.searchItem(itemICodeSearchTxt.getText());
            if(item!=null){
                itemICodeSearchTxt.setText(item.getCode());
                itemDescSearchTxt.setText(item.getDescription());
                itemQTYSearchTxt.setText(Integer.toString(item.getQty()));
                itemUPSearchTxt.setText(Double.toString(item.getUnitPrice()));
            }else{
                JOptionPane.showMessageDialog(this, "No Item Found..");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ThogaKadeMW.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemSearchBtActionPerformed
    
    private void itemSearchClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSearchClearBtnActionPerformed
        itemICodeSearchTxt.setText("");
        itemDescSearchTxt.setText("");
        itemQTYSearchTxt.setText("");
        itemUPSearchTxt.setText("");
        itemICodeSearchTxt.requestFocus();
    }//GEN-LAST:event_itemSearchClearBtnActionPerformed
    
    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton21ActionPerformed
    
    private void itemICodeUpdateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemICodeUpdateTxtActionPerformed
        try {
            String itemCode=itemICodeUpdateTxt.getText();
            this.itemCode=itemCode;
            Item item = itemController.searchItem(itemCode);
            if(item!=null){
                itemICodeUpdateTxt.setText(item.getCode());
                itemDescUpdateTxt.setText(item.getDescription());
                itemQTYUpdateTxt.setText(Integer.toString(item.getQty()));
                itemUPUpdateTxt.setText(Double.toString(item.getUnitPrice()));
            }else{
                JOptionPane.showMessageDialog(this, "No Item Found..");
                itemDescUpdateTxt.setText("");
                itemQTYUpdateTxt.setText("");
                itemUPUpdateTxt.setText("");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ThogaKadeMW.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemICodeUpdateTxtActionPerformed
    
    private void itemUpdateBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUpdateBtActionPerformed
        try {
            boolean isUpdated = itemController.updateItem(new Item(itemICodeUpdateTxt.getText(), itemDescUpdateTxt.getText(), Integer.parseInt(itemQTYUpdateTxt.getText()), Double.parseDouble(itemUPUpdateTxt.getText())));
            if(isUpdated){
                JOptionPane.showMessageDialog(this, "Item Updated Successfully !!");
                itemUpdateClearBtn.doClick();
                itemICodeUpdateTxt.requestFocus();
            }else{
                JOptionPane.showMessageDialog(this, "Item Update Falier !!");
                itemICodeUpdateTxt.requestFocus();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ThogaKadeMW.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemUpdateBtActionPerformed
    
    private void itemUpdateClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUpdateClearBtnActionPerformed
        itemICodeUpdateTxt.setText("");
        itemDescUpdateTxt.setText("");
        itemQTYUpdateTxt.setText("");
        itemUPUpdateTxt.setText("");
        itemICodeUpdateTxt.requestFocus();
    }//GEN-LAST:event_itemUpdateClearBtnActionPerformed
    
    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton24ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ViewStockForm(null, true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        
        this.setLocation(x-mouseX, y-mouseY);
    }//GEN-LAST:event_jLabel1MouseDragged
    
    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        mouseX=evt.getX();
        mouseY=evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//        */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ManageItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ManageItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ManageItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ManageItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ManageItemForm dialog = new ManageItemForm(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton itemAddBt;
    private javax.swing.JButton itemAddClearBtn;
    private javax.swing.JButton itemDeleteBt;
    private javax.swing.JButton itemDeleteClearBtn;
    private javax.swing.JTextField itemDescAddTxt;
    private javax.swing.JTextField itemDescDeleteTxt;
    private javax.swing.JTextField itemDescSearchTxt;
    private javax.swing.JTextField itemDescUpdateTxt;
    private javax.swing.JTextField itemICodeAddTxt;
    private javax.swing.JTextField itemICodeDeleteTxt;
    private javax.swing.JTextField itemICodeSearchTxt;
    private javax.swing.JTextField itemICodeUpdateTxt;
    private javax.swing.JTextField itemQTYAddTxt;
    private javax.swing.JTextField itemQTYDeleteTxt;
    private javax.swing.JTextField itemQTYSearchTxt;
    private javax.swing.JTextField itemQTYUpdateTxt;
    private javax.swing.JButton itemSearchBt;
    private javax.swing.JButton itemSearchClearBtn;
    private javax.swing.JTextField itemUPAddTxt;
    private javax.swing.JTextField itemUPDeleteTxt;
    private javax.swing.JTextField itemUPSearchTxt;
    private javax.swing.JTextField itemUPUpdateTxt;
    private javax.swing.JButton itemUpdateBt;
    private javax.swing.JButton itemUpdateClearBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton24;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}
